DEVICE_PATH := device/vivo/1907N

ALLOW_MISSING_DEPENDENCIES := true

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a75

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-2a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a55

TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_IS_64_BIT := true

TARGET_BOARD_PLATFORM := mt6768
TARGET_BOARD_PLATFORM_GPU := mali-g52mc2

TARGET_BOOTLOADER_BOARD_NAME := k68v1_64
TARGET_NO_BOOTLOADER := true

BOARD_HAS_MTK_HARDWARE := true
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true

TARGET_OTA_ASSERT_DEVICE := 1907N,vivo 1907,PD1913F_EX

BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 \
product.version=PD1913F_EX_A_9.10.0 \
fingerprint.abbr=12/SP1A.210812.003 \
region_ver=W20 \
product.solution=MTK \
androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x40078000
BOARD_PAGE_SIZE := 2048
BOARD_HASH_TYPE := sha1
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_RAMDISK_OFFSET := 0x07c08000
BOARD_KERNEL_SECOND_OFFSET := 0xbff88000
BOARD_TAGS_OFFSET := 0x0bc08000
BOARD_BOOT_HEADER_VERSION := 2
BOARD_DTBOIMG_PARTITION_SIZE := 193080
BOARD_DTB_SIZE := 98357
BOARD_DTB_OFFSET := 0x0bc08000

BOARD_MKBOOTIMG_ARGS += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_PAGE_SIZE)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_KERNEL_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --second_offset $(BOARD_KERNEL_SECOND_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)

BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x4000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x4000000
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_PARTITION_SIZE := 0x10000000
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x160000000
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x1af78f8000
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_PARTITION_SIZE := 0x80000000

BOARD_USES_VENDORIMAGE := true
TARGET_COPY_OUT_VENDOR := vendor

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := false
BOARD_USES_RECOVERY_AS_BOOT := false

BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
BOARD_SUPPRESS_SECURE_ERASE := true

# Kernel
BOARD_KERNEL_IMAGE_NAME := Image.gz
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image.gz
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64

TARGET_COPY_OUT_VENDOR := vendor

BOARD_AVB_ENABLE := true
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1
PLATFORM_SECURITY_PATCH := 2022-08-01
VENDOR_SECURITY_PATCH := 2021-11-05
PLATFORM_VERSION := 12

BOARD_AVB_RECOVERY_ADD_HASH_FOOTER_ARGS += \
    --prop com.android.build.boot.os_version:12 \
    --prop com.android.build.boot.security_patch:2019-06-06 \
    --prop com.android.build.system.os_version:12 \
    --prop com.android.build.system.security_patch:2022-08-01 \
    --prop com.android.build.vendor.os_version:12 \
    --prop com.android.build.vendor.security_patch:2021-11-05

# Storage & Encryption
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := false # the metadata partition on the device exists, but it is empty
TW_USE_FSCRYPT_POLICY := 1
TW_PREPARE_DATA_MEDIA_EARLY := true
TW_FORCE_KEYMASTER_VER := true
BOARD_USES_METADATA_PARTITION := true

# SELinux
#DEVICE_SEPOLICY_DIR := device/vivo/1907N/sepolicy
#SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += $(DEVICE_SEPOLICY_DIR)/public
#SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(DEVICE_SEPOLICY_DIR)/private
#BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_SEPOLICY_DIR)/vendor

# Modules & Binaries

TARGET_RECOVERY_DEVICE_MODULES += \
    ashmemd_aidl_interface-cpp \
    libashmemd_client \
    ashmemd \
    libtombstoned_client \
    tombstoned \
    liblog \
    libresetprop \
    libminijail \
    libminijail_vendor

RECOVERY_BINARY_SOURCE_FILES += \
    $(PRODUCT_OUT)/system/bin/ashmemd \
    $(PRODUCT_OUT)/system/bin/tombstoned

TW_INCLUDE_RESETPROP := true

TARGET_RECOVERY_DEVICE_MODULES += \
    libresetprop \
    libminijail \
    libminijail_vendor

TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += $(TARGET_OUT_SHARED_LIBRARIES)/libresetprop.so
TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += $(TARGET_OUT_SHARED_LIBRARIES)/libminijail.so

TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab
BOARD_HAS_NO_SELECT_BUTTON := true
RECOVERY_SDCARD_ON_DATA := true
TW_HAS_MTP := true
TW_INTERNAL_STORAGE_PATH := "/data/media/0"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "external_sd"
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_ROOT_EXTRA_FOLDERS := system_root

TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop
TARGET_RECOVERY_INITRC := $(DEVICE_PATH)/recovery/root/init.recovery.mt6768.rc

BOARD_VNDK_VERSION := current

TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TARGET_RECOVERY_LCD_BACKLIGHT_PATH := \"/sys/class/leds/lcd-backlight/brightness\"
TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 2000
TW_NO_SCREEN_BLANK := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm,vivo_ts_fp,gf-keys,ACCDET"

TW_THEME := portrait_hdpi
DEVICE_SCREEN_WIDTH := 1080
DEVICE_SCREEN_HEIGHT := 2340
TW_STATUS_BAR_STACKING_OFFSET := 70
TW_STATUS_BAR_PADDING_LEFT := 40
TW_STATUS_BAR_PADDING_RIGHT := 40
TW_CLOCK_OFFSET := 100

TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2340

TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_USE_TOOLBOX := true
TW_EXTRA_LANGUAGES := false
TW_DEFAULT_LANGUAGE := en
TW_INCLUDE_NTFS_3G := true
TARGET_USES_MKE2FS := true

TARGET_USE_CONFIGFS := true
TW_USB_CONFIGFS_STRINGS := true
TW_EXCLUDE_LUN_0 := true
TW_EXCLUDE_DEFAULT_USB_INIT := false
TARGET_RECOVERY_USB_ID_VENDOR := 0x2D95
TARGET_RECOVERY_USB_ID_PRODUCT := 0x6012

TWRP_INCLUDE_LOGCAT := true
TW_INCLUDE_FASTBOOTD := false
TARGET_USES_LOGD := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_APEX := true

TW_DEFAULT_DEVICE_NAME := vivo_V17_Neo
TW_DEVICE_VERSION := vivo 1907 - kavindren
