DEVICE_PATH := device/vivo/1907N

# OrangeFox Recovery Project
FOX_MAINTAINER_PATCH_VERSION := 1
FOX_BUILD_TYPE := Unofficial
OF_MAINTAINER := kavindren

# Partitions
FOX_RECOVERY_INSTALL_PARTITION := /dev/block/by-name/recovery
FOX_RECOVERY_SYSTEM_PARTITION := /dev/block/by-name/system
FOX_RECOVERY_VENDOR_PARTITION := /dev/block/by-name/vendor

# Base Architecture
ALLOW_MISSING_DEPENDENCIES := true
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a53

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_VARIANT := cortex-a53

TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_IS_64_BIT := true

# Platform
TARGET_BOARD_PLATFORM := mt6768
TARGET_BOARD_PLATFORM_GPU := mali-g52mc2
TARGET_BOOTLOADER_BOARD_NAME := k68v1_64
TARGET_NO_BOOTLOADER := true

BOARD_HAS_MTK_HARDWARE := true
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true

# Assertions
TARGET_OTA_ASSERT_DEVICE := 1907N,vivo 1907,PD1913F_EX

# Kernel Parameters
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 product.version=PD1913F_EX_A_9.9.39 fingerprint.abbr=12/SP1A.210812.003 region_ver=W20 product.solution=MTK androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x40078000
BOARD_PAGE_SIZE := 2048
BOARD_HASH_TYPE := sha1
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_RAMDISK_OFFSET := 0x07c08000
BOARD_KERNEL_SECOND_OFFSET := 0xbff88000
BOARD_TAGS_OFFSET := 0x0bc08000
BOARD_BOOT_HEADER_VERSION := 2
BOARD_DTBOIMG_PARTITION_SIZE := 193080
BOARD_DTB_SIZE := 98357
BOARD_DTB_OFFSET := 0x0bc08000

BOARD_MKBOOTIMG_ARGS += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_PAGE_SIZE)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_KERNEL_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --second_offset $(BOARD_KERNEL_SECOND_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)

# Images & File Systems
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x4000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x4000000
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_PARTITION_SIZE := 0x10000000
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x160000000
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x1af78f8000
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_PARTITION_SIZE := 0x80000000

BOARD_USES_VENDORIMAGE := true
TARGET_COPY_OUT_VENDOR := vendor

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
BOARD_USES_RECOVERY_AS_BOOT := false
BOARD_SUPPRESS_SECURE_ERASE := true

# Prebuilt Kernel & DTB
BOARD_KERNEL_IMAGE_NAME := Image.gz
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image.gz
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_KERNEL_ARCH := arm64

# Security & AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1
PLATFORM_SECURITY_PATCH := 2022-08-01
VENDOR_SECURITY_PATCH := 2021-11-05
PLATFORM_VERSION := 12

BOARD_AVB_RECOVERY_ADD_HASH_FOOTER_ARGS += \
    --prop com.android.build.boot.os_version:12 \
    --prop com.android.build.boot.security_patch:2019-06-06 \
    --prop com.android.build.system.os_version:12 \
    --prop com.android.build.system.security_patch:2022-08-01 \
    --prop com.android.build.vendor.os_version:12 \
    --prop com.android.build.vendor.security_patch:2021-11-05

# Storage & Encryption
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := false # the metadata partition on the device exists, but it is empty
TW_USE_FSCRYPT_POLICY := 1
TW_PREPARE_DATA_MEDIA_EARLY := true
TW_FORCE_KEYMASTER_VER := true
OF_DEFAULT_KEYMASTER_VERSION := 4.1
BOARD_USES_METADATA_PARTITION := true

# SELinux
#DEVICE_SEPOLICY_DIR := device/vivo/1907N/sepolicy
#SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += $(DEVICE_SEPOLICY_DIR)/public
#SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(DEVICE_SEPOLICY_DIR)/private
#BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_SEPOLICY_DIR)/vendor

# Modules & Binaries
TARGET_RECOVERY_DEVICE_MODULES += \
    ashmemd_aidl_interface-cpp \
    libashmemd_client \
    ashmemd \
    libtombstoned_client \
    tombstoned \
    liblog \
    libresetprop \
    libminijail \
    libminijail_vendor

RECOVERY_BINARY_SOURCE_FILES += \
    $(PRODUCT_OUT)/system/bin/ashmemd \
    $(PRODUCT_OUT)/system/bin/tombstoned

# Recovery UI & Functionality
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab
BOARD_HAS_NO_SELECT_BUTTON := true
RECOVERY_SDCARD_ON_DATA := true
TW_HAS_MTP := true
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_ROOT_EXTRA_FOLDERS := system_root
TARGET_RECOVERY_INITRC := $(DEVICE_PATH)/recovery/root/init.recovery.mt6768.rc
TW_NO_SCREEN_BLANK := true

# OrangeFox UI & Paths
OF_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
OF_MAX_BRIGHTNESS := 2167
OF_SCREEN_H := 2340
OF_STATUS_BAR_PADDING_TOP := 70
OF_STATUS_BAR_PADDING_LEFT := 40
OF_STATUS_BAR_PADDING_RIGHT := 40
OF_CLOCK_POS := 1 # Center
OF_USE_GREEN_LED := 0
FOX_ENABLE_APP_MANAGER := true
OF_ALLOW_DISABLE_NAVBAR := 0

TW_MAX_BRIGHTNESS := 2167
TW_DEFAULT_BRIGHTNESS := 2000

TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2340
TW_THEME := portrait_hdpi

# USB Config
TARGET_USE_CONFIGFS := true
TW_USB_CONFIGFS_STRINGS := true
TARGET_RECOVERY_USB_ID_VENDOR := 0x2D95
TARGET_RECOVERY_USB_ID_PRODUCT := 0x6012

# Misc
TWRP_INCLUDE_LOGCAT := true
TW_INCLUDE_FASTBOOTD := false # No need in fastbootD, since device isn't A/B
TARGET_USES_LOGD := true
TW_INCLUDE_NTFS_3G := true
TARGET_USES_MKE2FS := true
